name: Deploy to Vercel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # 수동 실행 트리거 추가

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install dependencies
        working-directory: ./profile-web
        run: npm install
  
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Pull Vercel Environment Information
        working-directory: ./profile-web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        
      - name: Build project with Vercel
        working-directory: ./profile-web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel build --prod --token=$VERCEL_TOKEN --name=jinhyeok --yes
        
      - name: Deploy to Vercel (Production)
        working-directory: ./profile-web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --token=$VERCEL_TOKEN --prod --name=jinhyeok --yes