name: Deploy to Vercel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # 수동 실행 트리거 추가

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Production - jinhyeok  # 원하는 이름으로 명시

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      #- name: Install dependencies
      #  run: npm install
        
      #- name: Build project
      #  run: npm run build
        
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Pull Vercel project settings
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --token=$VERCEL_TOKEN --yes --environment=production
        
      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --token=$VERCEL_TOKEN --prod